/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YatrasRouteImport } from './routes/yatras'
import { Route as TeerthasRouteImport } from './routes/teerthas'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as KnowledgePortalRouteImport } from './routes/knowledge-portal'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as DifferenceRouteImport } from './routes/difference'
import { Route as CustomYatraRouteImport } from './routes/custom-yatra'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YatrasIndexRouteImport } from './routes/yatras.index'
import { Route as TeerthasIndexRouteImport } from './routes/teerthas.index'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as YatrasExploreRouteImport } from './routes/yatras.explore'
import { Route as TeerthasExploreRouteImport } from './routes/teerthas.explore'
import { Route as InstitutionsSchoolRouteImport } from './routes/institutions.school'
import { Route as InstitutionsCorporateRouteImport } from './routes/institutions.corporate'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const YatrasRoute = YatrasRouteImport.update({
  id: '/yatras',
  path: '/yatras',
  getParentRoute: () => rootRouteImport,
} as any)
const TeerthasRoute = TeerthasRouteImport.update({
  id: '/teerthas',
  path: '/teerthas',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePortalRoute = KnowledgePortalRouteImport.update({
  id: '/knowledge-portal',
  path: '/knowledge-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const DifferenceRoute = DifferenceRouteImport.update({
  id: '/difference',
  path: '/difference',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomYatraRoute = CustomYatraRouteImport.update({
  id: '/custom-yatra',
  path: '/custom-yatra',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YatrasIndexRoute = YatrasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YatrasRoute,
} as any)
const TeerthasIndexRoute = TeerthasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeerthasRoute,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const YatrasExploreRoute = YatrasExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => YatrasRoute,
} as any)
const TeerthasExploreRoute = TeerthasExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => TeerthasRoute,
} as any)
const InstitutionsSchoolRoute = InstitutionsSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => InstitutionsRoute,
} as any)
const InstitutionsCorporateRoute = InstitutionsCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => InstitutionsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/custom-yatra': typeof CustomYatraRoute
  '/difference': typeof DifferenceRoute
  '/enquire': typeof EnquireRoute
  '/institutions': typeof InstitutionsRouteWithChildren
  '/knowledge-portal': typeof KnowledgePortalRoute
  '/methodology': typeof MethodologyRoute
  '/teerthas': typeof TeerthasRouteWithChildren
  '/yatras': typeof YatrasRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/institutions/corporate': typeof InstitutionsCorporateRoute
  '/institutions/school': typeof InstitutionsSchoolRoute
  '/teerthas/explore': typeof TeerthasExploreRoute
  '/yatras/explore': typeof YatrasExploreRoute
  '/admin/': typeof AdminIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/teerthas/': typeof TeerthasIndexRoute
  '/yatras/': typeof YatrasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-yatra': typeof CustomYatraRoute
  '/difference': typeof DifferenceRoute
  '/enquire': typeof EnquireRoute
  '/knowledge-portal': typeof KnowledgePortalRoute
  '/methodology': typeof MethodologyRoute
  '/admin/login': typeof AdminLoginRoute
  '/institutions/corporate': typeof InstitutionsCorporateRoute
  '/institutions/school': typeof InstitutionsSchoolRoute
  '/teerthas/explore': typeof TeerthasExploreRoute
  '/yatras/explore': typeof YatrasExploreRoute
  '/admin': typeof AdminIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/teerthas': typeof TeerthasIndexRoute
  '/yatras': typeof YatrasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/custom-yatra': typeof CustomYatraRoute
  '/difference': typeof DifferenceRoute
  '/enquire': typeof EnquireRoute
  '/institutions': typeof InstitutionsRouteWithChildren
  '/knowledge-portal': typeof KnowledgePortalRoute
  '/methodology': typeof MethodologyRoute
  '/teerthas': typeof TeerthasRouteWithChildren
  '/yatras': typeof YatrasRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/institutions/corporate': typeof InstitutionsCorporateRoute
  '/institutions/school': typeof InstitutionsSchoolRoute
  '/teerthas/explore': typeof TeerthasExploreRoute
  '/yatras/explore': typeof YatrasExploreRoute
  '/admin/': typeof AdminIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/teerthas/': typeof TeerthasIndexRoute
  '/yatras/': typeof YatrasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/custom-yatra'
    | '/difference'
    | '/enquire'
    | '/institutions'
    | '/knowledge-portal'
    | '/methodology'
    | '/teerthas'
    | '/yatras'
    | '/admin/login'
    | '/institutions/corporate'
    | '/institutions/school'
    | '/teerthas/explore'
    | '/yatras/explore'
    | '/admin/'
    | '/institutions/'
    | '/teerthas/'
    | '/yatras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/custom-yatra'
    | '/difference'
    | '/enquire'
    | '/knowledge-portal'
    | '/methodology'
    | '/admin/login'
    | '/institutions/corporate'
    | '/institutions/school'
    | '/teerthas/explore'
    | '/yatras/explore'
    | '/admin'
    | '/institutions'
    | '/teerthas'
    | '/yatras'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/custom-yatra'
    | '/difference'
    | '/enquire'
    | '/institutions'
    | '/knowledge-portal'
    | '/methodology'
    | '/teerthas'
    | '/yatras'
    | '/admin/login'
    | '/institutions/corporate'
    | '/institutions/school'
    | '/teerthas/explore'
    | '/yatras/explore'
    | '/admin/'
    | '/institutions/'
    | '/teerthas/'
    | '/yatras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomYatraRoute: typeof CustomYatraRoute
  DifferenceRoute: typeof DifferenceRoute
  EnquireRoute: typeof EnquireRoute
  InstitutionsRoute: typeof InstitutionsRouteWithChildren
  KnowledgePortalRoute: typeof KnowledgePortalRoute
  MethodologyRoute: typeof MethodologyRoute
  TeerthasRoute: typeof TeerthasRouteWithChildren
  YatrasRoute: typeof YatrasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yatras': {
      id: '/yatras'
      path: '/yatras'
      fullPath: '/yatras'
      preLoaderRoute: typeof YatrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teerthas': {
      id: '/teerthas'
      path: '/teerthas'
      fullPath: '/teerthas'
      preLoaderRoute: typeof TeerthasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-portal': {
      id: '/knowledge-portal'
      path: '/knowledge-portal'
      fullPath: '/knowledge-portal'
      preLoaderRoute: typeof KnowledgePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/difference': {
      id: '/difference'
      path: '/difference'
      fullPath: '/difference'
      preLoaderRoute: typeof DifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-yatra': {
      id: '/custom-yatra'
      path: '/custom-yatra'
      fullPath: '/custom-yatra'
      preLoaderRoute: typeof CustomYatraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yatras/': {
      id: '/yatras/'
      path: '/'
      fullPath: '/yatras/'
      preLoaderRoute: typeof YatrasIndexRouteImport
      parentRoute: typeof YatrasRoute
    }
    '/teerthas/': {
      id: '/teerthas/'
      path: '/'
      fullPath: '/teerthas/'
      preLoaderRoute: typeof TeerthasIndexRouteImport
      parentRoute: typeof TeerthasRoute
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/yatras/explore': {
      id: '/yatras/explore'
      path: '/explore'
      fullPath: '/yatras/explore'
      preLoaderRoute: typeof YatrasExploreRouteImport
      parentRoute: typeof YatrasRoute
    }
    '/teerthas/explore': {
      id: '/teerthas/explore'
      path: '/explore'
      fullPath: '/teerthas/explore'
      preLoaderRoute: typeof TeerthasExploreRouteImport
      parentRoute: typeof TeerthasRoute
    }
    '/institutions/school': {
      id: '/institutions/school'
      path: '/school'
      fullPath: '/institutions/school'
      preLoaderRoute: typeof InstitutionsSchoolRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/institutions/corporate': {
      id: '/institutions/corporate'
      path: '/corporate'
      fullPath: '/institutions/corporate'
      preLoaderRoute: typeof InstitutionsCorporateRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InstitutionsRouteChildren {
  InstitutionsCorporateRoute: typeof InstitutionsCorporateRoute
  InstitutionsSchoolRoute: typeof InstitutionsSchoolRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
}

const InstitutionsRouteChildren: InstitutionsRouteChildren = {
  InstitutionsCorporateRoute: InstitutionsCorporateRoute,
  InstitutionsSchoolRoute: InstitutionsSchoolRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
}

const InstitutionsRouteWithChildren = InstitutionsRoute._addFileChildren(
  InstitutionsRouteChildren,
)

interface TeerthasRouteChildren {
  TeerthasExploreRoute: typeof TeerthasExploreRoute
  TeerthasIndexRoute: typeof TeerthasIndexRoute
}

const TeerthasRouteChildren: TeerthasRouteChildren = {
  TeerthasExploreRoute: TeerthasExploreRoute,
  TeerthasIndexRoute: TeerthasIndexRoute,
}

const TeerthasRouteWithChildren = TeerthasRoute._addFileChildren(
  TeerthasRouteChildren,
)

interface YatrasRouteChildren {
  YatrasExploreRoute: typeof YatrasExploreRoute
  YatrasIndexRoute: typeof YatrasIndexRoute
}

const YatrasRouteChildren: YatrasRouteChildren = {
  YatrasExploreRoute: YatrasExploreRoute,
  YatrasIndexRoute: YatrasIndexRoute,
}

const YatrasRouteWithChildren =
  YatrasRoute._addFileChildren(YatrasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomYatraRoute: CustomYatraRoute,
  DifferenceRoute: DifferenceRoute,
  EnquireRoute: EnquireRoute,
  InstitutionsRoute: InstitutionsRouteWithChildren,
  KnowledgePortalRoute: KnowledgePortalRoute,
  MethodologyRoute: MethodologyRoute,
  TeerthasRoute: TeerthasRouteWithChildren,
  YatrasRoute: YatrasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
